theme: minima
title: Test blog page
author: b schouteten

description: Blog about the journey to get verilog simulations going with verilator

email: b_schouteten@hotmail.com
github_username: bschouteten
linkedin_username: https://www.linkedin.com/in/bjornschouteten/
