theme: minima
title: Test blog page
author: bschouteten

description: Blog about the journey to get simulations going with verilator

email: b_schouteten@hotmail.com
github_username: bschouteten
linkedin_username: [bjornschouteten](https://www.linkedin.com/in/bjornschouteten/)